/**
 * Airtable Types - Auto-generated
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Generated from Airtable Metadata API
 * Generated at: 2026-02-02T15:51:50.692Z
 * Base ID: app359c17lK0Ta8Ws
 * 
 * To regenerate: npm run generate:types
 */

/**
 * Lead table
 * Table ID: tblKIZ9CDjcQorONA
 * Generated from Airtable Metadata API
 */
export interface AirtableLead {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldFVsIGHZkLvnp5O) */
    ID: string;
    /** dateTime field (fldo1bSuO1yjHXjkL) */
    Data?: string;
    /** multipleRecordLinks field (fldPOa4TYVKbLiJTa) */
    Referenza?: string[];
    /** multipleLookupValues field (fldoCxUXtxrl6J7OJ) */
    'Nome referenza'?: string | string[];
    /** multipleRecordLinks field (fldCoDBMqa36c2jJ2) */
    Fonte?: string[];
    /** singleLineText field (fldKeDrS1XiJ47Prc) */
    Nome?: string;
    /** singleSelect field (fld42I37Sfnphcmza) */
    Gender?: 'male' | 'female' | 'unknown';
    /** singleLineText field (fldJJO2MU9E1Q0U6I) */
    Telefono?: string;
    /** email field (fldM2RXG7aRwGXLZU) */
    Email?: string;
    /** multilineText field (fldyt6SwpuJfROOd2) */
    Indirizzo?: string;
    /** number field (fldIzZxsJ9oRQIQy8) */
    CAP?: number;
    /** singleLineText field (fldgTqcRN7Ce4hPrk) */
    Città?: string;
    /** multilineText field (fld7ALmK1onyIj1zX) */
    Esigenza?: string;
    /** singleSelect field (fldzDSwT9nKOnbkan) */
    Stato?: 'Nuovo' | 'Contattato' | 'Qualificato' | 'In Negoziazione' | 'Cliente' | 'Perso' | 'Sospeso';
    /** multilineText field (fldoI9OwYbSTJuDmE) */
    Allegati?: string;
    /** multipleRecordLinks field (fldu170X3rbZBaGdj) */
    Assegnatario?: string[];
    /** singleLineText field (fldL4vLMGuXMCs9yA) */
    Ordini?: string;
    /** multipleRecordLinks field (fldkdo2z38CnPc3Uk) */
    Attività?: string[];
    /** multipleRecordLinks field (fld0mxht6l5onjOfT) */
    'From field: Referenza'?: string[];
    /** multipleRecordLinks field (fld4NKnBTOB0g1QYs) */
    Notes?: string[];
    /** singleLineText field (fldoD2h8AYJf3zx23) */
    Conversations?: string;
    /** singleLineText field (fldwRJVejr2Grk4e8) */
    Order?: string;
    /** multipleRecordLinks field (fldZj5OaJQQwyIHRt) */
    Orders?: string[];
  };
}

/**
 * Activity table
 * Table ID: tblbcuRXKrWvne0Wy
 * Generated from Airtable Metadata API
 */
export interface AirtableActivity {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fld6pXq1O74quaBeM) */
    ID: string;
    /** multipleRecordLinks field (fldl9Pzx0SnlSrkXv) */
    'ID Lead'?: string[];
    /** multipleLookupValues field (fldjTRENBzctRrCGL) */
    'Nome Lead': string;
    /** multipleRecordLinks field (fldY0qOsEB266QoZ8) */
    Assegnatario?: string[];
    /** multipleLookupValues field (fld1tvUfoVtr9G9PK) */
    'Nome Assegnatario': string;
    /** formula field (fldMHDDUqDvOOCLTt) */
    Titolo: string;
    /** singleSelect field (fldcR1a25ViHoT3mY) */
    Tipo?: 'Chiamata' | 'WhatsApp' | 'Email' | 'SMS' | 'Consulenza' | 'Follow-up' | 'Altro';
    /** singleSelect field (fldcEU2D7zwwj28bS) */
    Stato?: 'Da Pianificare' | 'Pianificata' | 'In corso' | 'In attesa' | 'Completata' | 'Annullata' | 'Rimandata';
    /** dateTime field (fldPvGAPV9iYGKvtJ) */
    Data?: string;
    /** duration field (fldpBB4UKATOiXLru) */
    'Durata stimata'?: any;
    /** singleSelect field (fldDA3bPMzKloIWa2) */
    Obiettivo?: 'Primo contatto' | 'Qualificazione lead' | 'Presentazione prodotto' | 'Invio preventivo' | 'Follow-up preventivo' | 'Negoziazione' | 'Chiusura ordine' | 'Fissare appuntamento' | 'Confermare appuntamento' | 'Promemoria appuntamento' | 'Consegna prodotto' | 'Assistenza tecnica' | 'Controllo soddisfazione' | 'Upsell Cross-sell' | 'Richiesta recensione';
    /** singleSelect field (fldjihrvpzgl1bc4h) */
    Priorità?: 'Bassa' | 'Media' | 'Alta' | 'Urgente';
    /** multilineText field (fldrcsQBXJAbwXtJX) */
    Note?: string;
    /** singleSelect field (fldaY6kTm1VVtZgGm) */
    Esito?: 'Contatto riuscito' | 'Nessuna risposta' | 'Numero errato' | 'Non disponibile' | 'Non presentato' | 'Molto interessato' | 'Interessato' | 'Poco interessato' | 'Non interessato' | 'Informazioni raccolte' | 'Preventivo richiesto' | 'Preventivo inviato' | 'Appuntamento fissato' | 'Ordine confermato' | 'Opportunità persa' | 'Servizio completato' | 'Problema risolto' | 'Cliente soddisfatto' | 'Recensione ottenuta';
    /** singleSelect field (fldrJg8nLxcJP4hbF) */
    'Prossima azione'?: 'Chiamata' | 'WhatsApp' | 'Email' | 'SMS' | 'Consulenza' | 'Follow-up' | 'Nessuna';
    /** dateTime field (fldS3v6etzoTOExOP) */
    'Data prossima azione'?: string;
    /** multilineText field (fldPcEwR5jCyIhPvC) */
    Allegati?: string;
    /** createdTime field (fldy429iW236noQ8B) */
    'Creato il '?: any;
    /** lastModifiedTime field (fldzEZhPBXa68idd0) */
    'Ultima modifica'?: any;
    /** singleLineText field (fldSDUhq6QLMQPOsz) */
    Order?: string;
  };
}

/**
 * Notes table
 * Table ID: tblmvBiXtpQ2Qm0C7
 * Generated from Airtable Metadata API
 */
export interface AirtableNotes {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldQ9C8FopcgY5olR) */
    ID: string;
    /** multipleRecordLinks field (fldnNg4T43UMokhNB) */
    Lead?: string[];
    /** multipleRecordLinks field (fldV9X9o3K9xNgbka) */
    User?: string[];
    /** multilineText field (fldcN1Bb8fjT46OyO) */
    Content?: string;
    /** singleSelect field (fldEe2eW9PboYAcRS) */
    Type?: 'Riflessione' | 'Promemoria' | 'Follow-up' | 'Info Cliente';
    /** checkbox field (flduQTxMKNqGqe5i8) */
    Pinned?: boolean;
    /** createdTime field (fldY6MDn5uxeCtkBA) */
    CreatedAt?: any;
  };
}

/**
 * User table
 * Table ID: tbl141xF7ZQskCqGh
 * Generated from Airtable Metadata API
 */
export interface AirtableUser {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldTcrLFlAu7xd3xd) */
    ID: string;
    /** singleLineText field (fldPuUTYFd9Ln9LyK) */
    Nome?: string;
    /** email field (fld5F70WsIXmO7Jmr) */
    Email?: string;
    /** checkbox field (fld7y6Wq3Rgggc7nb) */
    Attivo?: boolean;
    /** singleSelect field (fldFoPbzvdL39ZLWV) */
    Ruolo?: 'Admin' | 'Sales';
    /** phoneNumber field (fldICIhUTA2KIrx5s) */
    Telefono?: string;
    /** multipleRecordLinks field (flddIU6nf39fivElY) */
    Activity?: string[];
    /** multipleRecordLinks field (fldtEVUcSYMyioncZ) */
    Lead?: string[];
    /** multipleRecordLinks field (fldY1HqSbYus6Pteq) */
    Automations?: string[];
    /** singleLineText field (fldbo4AIlMX7FSyJt) */
    Password?: string;
    /** url field (fldrHmmV8pAzaMU46) */
    Avatar_URL?: string;
    /** multipleRecordLinks field (fldjiodCTOFhX8Upu) */
    Orders?: string[];
    /** multipleRecordLinks field (fld5vnck9OAmFgDrj) */
    Commission_Payments?: string[];
    /** singleLineText field (fldtBeb2r7gA6HJWS) */
    AI_Conversations?: string;
    /** multipleRecordLinks field (fldiQQFLoTV7efMjv) */
    Notes?: string[];
  };
}

/**
 * Automations table
 * Table ID: tblSd4GAZo9yHQvG0
 * Generated from Airtable Metadata API
 */
export interface AirtableAutomations {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldER6lYod0IkPSZH) */
    ID: string;
    /** singleLineText field (fld7UCuiiSPzduZiU) */
    Name?: string;
    /** singleSelect field (fldLB8NTUKbbTjqSj) */
    Category?: 'Gestione Lead' | 'Gestione Activity' | 'Gestione Order' | 'Gestione Products' | 'Gestione User' | 'Sistema' | 'Report' | 'Pulizia Dati';
    /** singleSelect field (fldFD9hyBeFGhFpaU) */
    Priority?: 'Bassa' | 'Media' | 'Alta' | 'Critica';
    /** checkbox field (fld6LSkcukbmhSgFn) */
    IsActive?: boolean;
    /** singleSelect field (fldbl26ucKOv47Nfy) */
    TriggerTable?: 'Lead' | 'Activity' | 'Order' | 'Products' | 'User' | 'System';
    /** singleSelect field (fldZhjH5BrMzfrnQ8) */
    TriggerEvent?: 'Record Created' | 'Record Updated' | 'Record Deleted';
    /** singleLineText field (fldcbulewcZv9x8E0) */
    TriggerField?: string;
    /** singleSelect field (fldsiCrx99OZAc6mi) */
    TriggerOperator?: 'equals' | 'not_equals' | 'contains' | 'is_empty' | 'is_not_empty';
    /** singleSelect field (fld82PjklhSCyBqut) */
    TriggerOperator2?: 'equals' | 'not_equals' | 'contains' | 'is_empty' | 'is_not_empty';
    /** singleLineText field (fldsJKwzYPAp0gpjq) */
    TriggerValue?: string;
    /** singleLineText field (fldeVWXtoZeurnf60) */
    TriggerValue2?: string;
    /** date field (fldT40thLOuKETzBX) */
    LastExecuted?: string;
    /** number field (fldDprmtNnxB9wbCz) */
    ExecutionCount?: number;
    /** multipleRecordLinks field (fldUz1TRvalxuYfFL) */
    CreatedBy?: string[];
    /** multilineText field (fldf3XGjuOxwoPtp2) */
    Description?: string;
    /** singleSelect field (fldxTKv52oidsVOgY) */
    ActionType?: 'update_field' | 'create_activity' | 'send_notification';
    /** singleSelect field (fldea86uuuN6fgKyJ) */
    ActionTargetTable?: 'Lead' | 'Activity' | 'Order' | 'User';
    /** singleLineText field (fldBMRaRVEgxyggUx) */
    ActionTargetField?: string;
    /** singleLineText field (fldScr0u094iiIGEy) */
    ActionValue?: string;
    /** singleLineText field (fld6Peej0Yj1mcbGe) */
    TriggerField2?: string;
    /** singleSelect field (fld3JQ1ij2TMGQbdl) */
    TriggerLogic?: 'AND' | 'OR';
  };
}

/**
 * Products table
 * Table ID: tblEFvr3aT2jQdYUL
 * Generated from Airtable Metadata API
 */
export interface AirtableProducts {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** singleLineText field (fldf5PKjtvf3P9BSf) */
    Codice_Matrice?: string;
    /** singleLineText field (fldnfP2LuK00IeR83) */
    Nome_Prodotto?: string;
    /** multilineText field (fld0g5uzN3scrhewX) */
    Metadata?: string;
    /** multilineText field (fld7udAiJPd0lxR2M) */
    Descrizione?: string;
    /** singleSelect field (fldCMCaLlXpQYoT2d) */
    Categoria?: 'Materassi' | 'Reti' | 'Cuscini' | 'Letti' | 'Accessori' | 'Altro';
    /** currency field (fldrrD3mW6B0KPDv5) */
    Prezzo_Listino_Attuale?: number;
    /** currency field (fld6mXCvw3WZ24PH1) */
    Costo_Attuale?: number;
    /** percent field (fld8pq835edGJruAP) */
    Margine_Standard?: number;
    /** multipleAttachments field (fld6blsbk5MH1QJsl) */
    Foto_Prodotto?: Array<{ id: string; url: string; filename: string; size: number; type: string }>;
    /** multipleAttachments field (fldxtFQZgmNUiODEj) */
    Schede_Tecniche?: Array<{ id: string; url: string; filename: string; size: number; type: string }>;
    /** multipleAttachments field (fldDmxM7yKC5PH7OH) */
    Manuali?: Array<{ id: string; url: string; filename: string; size: number; type: string }>;
    /** multipleAttachments field (fldKfcHq8EOreZeNi) */
    Certificazioni?: Array<{ id: string; url: string; filename: string; size: number; type: string }>;
    /** checkbox field (fldH21aOdPe6q5Hwe) */
    Attivo?: boolean;
    /** checkbox field (fld2pmubbYdlqou3W) */
    In_Evidenza?: boolean;
    /** multipleRecordLinks field (fldcTbEStsa1OXEhc) */
    Product_Variants?: string[];
    /** multipleRecordLinks field (fldk8bWtscU83cgts) */
    Product_Price_History?: string[];
    /** multipleRecordLinks field (fldAc77TrLphlTvuV) */
    Order_Items?: string[];
  };
}

/**
 * Product_Variants table
 * Table ID: tblGnZgea6HlO2pJ4
 * Generated from Airtable Metadata API
 */
export interface AirtableProductVariants {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldCyKxW7OtVzruuD) */
    ID_Variante: string;
    /** multipleRecordLinks field (fldPOTbVPXlwSv8CX) */
    ID_Prodotto?: string[];
    /** singleLineText field (fld76sosPd6N9CyYM) */
    Tipo_Variante?: string;
    /** singleLineText field (fldyUMyeLliWoa5CP) */
    Codice_Variante?: string;
    /** singleLineText field (fldNAjiLucHjGQArQ) */
    Nome_Variante?: string;
    /** multilineText field (fldZz8UM21ABwwNvJ) */
    Descrizione_Variante?: string;
    /** currency field (fldrszGsOcpwNfb6M) */
    Prezzo_Aggiuntivo_Attuale?: number;
    /** currency field (fldeTUHJMy6a0qcTc) */
    Costo_Aggiuntivo_Attuale?: number;
    /** number field (fldn5nJx0KhnWqCwi) */
    Posizione?: number;
    /** checkbox field (fldbt0RXTaIkMd1uF) */
    Attivo?: boolean;
    /** multipleRecordLinks field (fldaMVNaGzS9mtKpE) */
    Product_Price_History?: string[];
    /** multipleRecordLinks field (fldPkRbJEjzuFdtzF) */
    Order_Items?: string[];
    /** multipleRecordLinks field (flduMIWF7H4h3E18r) */
    Product_Structures?: string[];
  };
}

/**
 * Product_Structures table
 * Table ID: tbl58tZxGfEnLpUZA
 * Generated from Airtable Metadata API
 */
export interface AirtableProductStructures {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldQbrcmblGqdC7uK) */
    ID_Struttura: string;
    /** singleLineText field (fldgqiEUXdssXskHP) */
    Nome?: string;
    /** multilineText field (fld1mSHas3qImJlCW) */
    Descrizione?: string;
    /** multilineText field (fldNYgShbWYl54lbn) */
    Campi_JSON?: string;
    /** checkbox field (fldmCDyiPiLc2z03p) */
    Attiva?: boolean;
    /** createdTime field (fldkcnayxkyHb1U0q) */
    Data_Creazione?: any;
    /** lastModifiedTime field (fldNexSklGqEc9PvK) */
    Data_Modifica?: any;
    /** multipleRecordLinks field (fldOmV1x9AjTXS7Rd) */
    Product_Variants?: string[];
  };
}

/**
 * Orders table
 * Table ID: tblkqfCMabBpVD1fP
 * Generated from Airtable Metadata API
 */
export interface AirtableOrders {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldKZoq9URhNahDQi) */
    ID_Ordine: string;
    /** multipleRecordLinks field (fld3dZM6IrbRLdXhg) */
    ID_Lead?: string[];
    /** multipleRecordLinks field (flduS5UnHPMVTi7j3) */
    ID_Venditore?: string[];
    /** date field (fldV3eolPCwWr6pmn) */
    Data_Ordine?: string;
    /** date field (fldFMgVfdak8c9AEY) */
    Data_Consegna_Richiesta?: string;
    /** singleSelect field (fldsFQI58A858ybfQ) */
    Stato_Ordine?: 'Bozza' | 'Confermato' | 'In Produzione' | 'Spedito' | 'Consegnato' | 'Annullato';
    /** singleSelect field (fldLpW7xlQ1e5ruKE) */
    Stato_Pagamento?: 'Non Pagato' | 'Pagamento Parziale' | 'Pagato' | 'Rimborsato';
    /** singleSelect field (fldV0IITHIiM8EArD) */
    Modalita_Pagamento?: 'Contanti' | 'Bonifico' | 'Carta Credito' | 'Finanziamento' | 'Assegno' | 'PayPal';
    /** currency field (fldzanwXkVjZVAsmk) */
    Totale_Lordo?: number;
    /** currency field (fldNFWpxKbHrAjK7M) */
    Totale_Sconto?: number;
    /** currency field (fldIZtRCPezW5V9xd) */
    Totale_Netto?: number;
    /** currency field (fldCwlLWBLvsVfb1D) */
    Totale_IVA?: number;
    /** currency field (fldsxbpf65whI1AQ9) */
    Totale_Finale?: number;
    /** number field (fldtvGAvNTrZ8G8Ny) */
    Percentuale_Sconto?: number;
    /** number field (fld4sYLFUwPmuqHBn) */
    Percentuale_Commissione?: number;
    /** currency field (fldvgndBHQEVxGmRp) */
    Importo_Commissione?: number;
    /** multilineText field (fldnGa1Jn46EnhtkZ) */
    Indirizzo_Consegna?: string;
    /** multilineText field (fldWhtHJPher9BpFG) */
    Note_Cliente?: string;
    /** multilineText field (fldgrJvkrUElCjlOf) */
    Note_Interne?: string;
    /** singleLineText field (fldPwKEhLNO4xDnNI) */
    Codice_Tracking?: string;
    /** checkbox field (fld58fCIeramxdmMU) */
    Finanziamento_Richiesto?: boolean;
    /** currency field (fldm2OP4lliO6RsLW) */
    Rata_Mensile?: number;
    /** number field (fldIqwzaEKIsEHOyQ) */
    Numero_Rate?: number;
    /** number field (fldtA2U6vTFMJNAP2) */
    Tasso_Interesse?: number;
    /** singleSelect field (fldG6mIbWvMDIz0xy) */
    Stato_Finanziamento?: 'Non_Richiesto' | 'In_Valutazione' | 'Approvato' | 'Rifiutato';
    /** dateTime field (fldvrdaW7q95QqBXb) */
    Data_Creazione?: string;
    /** dateTime field (fldvPeT9zhUvbeXaT) */
    Ultima_Modifica?: string;
    /** multipleRecordLinks field (fldZzH34LRo1JHMN9) */
    Order_Items?: string[];
    /** multipleRecordLinks field (fldZCBePkAYMaODUL) */
    Commission_Payments?: string[];
    /** multipleRecordLinks field (fldwAKt1c4Mw7M1ra) */
    Payment_Transactions?: string[];
    /** multilineText field (fldK2r2c1OwqRlADt) */
    URL_Contratto?: string;
    /** multilineText field (fldojXdvvx7o0Dg8m) */
    URL_Documenti_Cliente?: string;
    /** multilineText field (fldlE65U4fgLVCCH2) */
    URL_Schede_Cliente?: string;
  };
}

/**
 * Order_Items table
 * Table ID: tblxzhMCa5UJOMZqC
 * Generated from Airtable Metadata API
 */
export interface AirtableOrderItems {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldpVEjQiKnH2xJBG) */
    ID_Riga: string;
    /** multipleRecordLinks field (fldBiodqrYsNVjq8X) */
    ID_Ordine?: string[];
    /** multipleRecordLinks field (fldZGeKUdK49WaCJD) */
    ID_Prodotto?: string[];
    /** multipleRecordLinks field (fldKWCrN5sxh7ImNq) */
    Configurazione_Varianti?: string[];
    /** number field (fld5ibYJnA4cHfjIC) */
    Quantita?: number;
    /** currency field (fldDoZkNQXaVaxwHt) */
    Prezzo_Unitario?: number;
    /** currency field (fldYTHV2SfEHsI2zw) */
    Costo_Unitario?: number;
    /** number field (fld1efGweweGNUGBI) */
    Sconto_Percentuale?: number;
    /** currency field (fldLYb17RcQ7c4Guy) */
    Sconto_Importo?: number;
    /** currency field (fldK6kceQ1nXwVjGp) */
    Prezzo_Finale_Unitario?: number;
    /** currency field (fldh0fpTAsgMVv1wb) */
    Totale_Riga?: number;
    /** multilineText field (fld5pqeewU5Y65No4) */
    Configurazione_JSON?: string;
    /** multilineText field (fld0Rhbd0xBYUJhpi) */
    Note_Configurazione?: string;
    /** singleLineText field (fldsPYCm1tKKOllhH) */
    Codice_Prodotto_Configurato?: string;
    /** singleLineText field (fldJgF6dCdeA8pyPt) */
    Nome_Prodotto_Personalizzato?: string;
    /** singleLineText field (fldjSBenztZeD7nqF) */
    Dimensioni_Finali?: string;
    /** number field (fldwqX4QPTl2Mmw2A) */
    Peso_Stimato?: number;
  };
}

/**
 * Product_Price_History table
 * Table ID: tblXtMoiDwLEBG5WE
 * Generated from Airtable Metadata API
 */
export interface AirtableProductPriceHistory {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldaCyE6tzocxKRlj) */
    ID_Storico: string;
    /** multipleRecordLinks field (flddACnZLYJL3LUJH) */
    ID_Prodotto?: string[];
    /** multipleRecordLinks field (fldHqRKbtjOWWgNDY) */
    ID_Variante?: string[];
    /** currency field (fldj5iNYRp1bJ64KN) */
    Prezzo_Vendita?: number;
    /** currency field (fldPltua8MDcN4Gd2) */
    Prezzo_Costo?: number;
    /** date field (fldF0uXIqWYvfrJGP) */
    Data_Validita_Da?: string;
    /** date field (fld77YoRDp2qCxfLw) */
    Data_Validita_A?: string;
    /** singleSelect field (fldDeaxMBDaOihCys) */
    Tipo_Prezzo?: 'Base' | 'Promo' | 'Scontato' | 'Speciale';
    /** singleSelect field (fld0T1C93vYkMJ5Zc) */
    Motivo_Cambio?: 'Aggiornamento_Listino' | 'Promozione' | 'Correzione_Errore' | 'Cambio_Fornitore' | 'Inflazione';
    /** singleLineText field (fldAjxoYpvtrLn5Xc) */
    Creato_Da?: string;
    /** multilineText field (fldMYMZCoia4CGtod) */
    Note?: string;
    /** checkbox field (fldoNP68tyFOlqbFA) */
    Attivo?: boolean;
  };
}

/**
 * Commission_Payments table
 * Table ID: tblbn6gRCwpmYICdZ
 * Generated from Airtable Metadata API
 */
export interface AirtableCommissionPayments {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldduD2yGgg5ooVSo) */
    ID_Commissione: string;
    /** multipleRecordLinks field (fldVBnrujZJSavXF0) */
    ID_Ordine?: string[];
    /** multipleRecordLinks field (fldcgx9z01MkxV2uY) */
    ID_Venditore?: string[];
    /** currency field (fldIhn4XKXq2y2XaG) */
    Importo_Vendita?: number;
    /** number field (fldG68DX0OaI5AFvW) */
    Percentuale_Commissione?: number;
    /** currency field (fld8RnUcpQTGA80zh) */
    Importo_Commissione?: number;
    /** date field (fldqZV2CbUJduUDR9) */
    Data_Maturazione?: string;
    /** date field (fld2ma2KCLV4rX4uC) */
    Data_Pagamento?: string;
    /** singleSelect field (fldrETFE4izxd4XEQ) */
    Stato_Pagamento?: 'Da_Pagare' | 'Pagato' | 'Sospeso' | 'Annullato';
    /** singleSelect field (fldLOqQgik5WjzZGE) */
    Modalita_Pagamento?: 'Bonifico' | 'Contanti' | 'Assegno' | 'Trattenuta';
    /** singleLineText field (fld5g4LSmO5epKyXF) */
    Numero_Bonifico?: string;
    /** singleLineText field (fldk8AATAaPf211Ih) */
    IBAN_Destinazione?: string;
    /** multilineText field (fldpDOagN29h8ImUj) */
    Note_Pagamento?: string;
    /** singleLineText field (fldHxUx8wEgzVXOGU) */
    Riferimento_Contabile?: string;
    /** singleLineText field (flddHdcI7UK3hDeCt) */
    Trimestre_Competenza?: string;
    /** number field (fldcpjfnTaWNAnq4b) */
    Anno_Competenza?: number;
    /** dateTime field (fldZom2FDILD0cVi1) */
    Data_Creazione?: string;
    /** url field (fldkTQd5ekgYQMFZO) */
    URL_Ricevuta_Commissione?: string;
    /** url field (fld5Vp3xeR4Wx09I4) */
    URL_Documento_Pagamento?: string;
  };
}

/**
 * Payment_Transactions table
 * Table ID: tbl2bzbSxMDch72CY
 * Generated from Airtable Metadata API
 */
export interface AirtablePaymentTransactions {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldA4ErjpIsMCCmtF) */
    ID_Transazione: string;
    /** multipleRecordLinks field (fldpkihjNEE12t6r4) */
    ID_Ordine?: string[];
    /** currency field (fldXf4lCwTrk4Zibu) */
    Importo?: number;
    /** dateTime field (fldhUF5Jx0FhJ9d8F) */
    Data_Transazione?: string;
    /** singleSelect field (fldhYMNN6aio3BsbG) */
    Tipo_Transazione?: 'Acconto' | 'Saldo' | 'Pagamento_Completo' | 'Rimborso' | 'Storno';
    /** singleSelect field (fld2UPiUFEi6toAZ1) */
    Modalita_Pagamento?: 'Contanti' | 'Bonifico' | 'Carta_Credito' | 'Carta_Debito' | 'PayPal' | 'Assegno' | 'Finanziamento';
    /** singleSelect field (fldICiPK2q9t3OMpm) */
    Stato_Transazione?: 'Pending' | 'Completata' | 'Fallita' | 'Annullata' | 'Rimborsata';
    /** singleLineText field (fldcQcaJZ6I7VRJHe) */
    Riferimento_Esterno?: string;
    /** singleLineText field (fldAxGfsPwRmXKqFo) */
    ID_Transazione_Gateway?: string;
    /** singleLineText field (fldbIaeAkNeKAlq3i) */
    Codice_Autorizzazione?: string;
    /** singleLineText field (fldVoHEVeRlCNtNBC) */
    Numero_Ricevuta?: string;
    /** singleLineText field (fldrVa2azls9lGiKe) */
    IBAN_Mittente?: string;
    /** singleLineText field (fldA6wWnvw9yEDIPq) */
    Nome_Titolare?: string;
    /** currency field (fldiRhsuYt9AV5K44) */
    Commissioni_Gateway?: number;
    /** number field (fldHsauxSn8ijnArZ) */
    Tasso_Cambio?: number;
    /** singleLineText field (fldSmvxOyFIuf5F5Q) */
    Valuta_Originale?: string;
    /** number field (fldhUgjbntWh29NFd) */
    Importo_Originale?: number;
    /** multilineText field (fldMQHHx8hz5V1Sbp) */
    Note_Transazione?: string;
    /** date field (fldFDNrX2RxQO2Gix) */
    Data_Accredito?: string;
    /** checkbox field (fldrWXMCtaOOYsDth) */
    Verificata?: boolean;
    /** checkbox field (fldDnCqmbf8ZppYyF) */
    Riconciliata?: boolean;
    /** multilineText field (fld4WDRq6VYdljqfA) */
    Log_Errori?: string;
    /** url field (fldNns13uGEBU0Y7n) */
    URL_Ricevuta?: string;
    /** url field (fld3Kvr2PGtXr0B82) */
    URL_Screenshot_Gateway?: string;
    /** url field (fldEG1rO1KX1iqEyw) */
    URL_Documento_Rimborso?: string;
    /** url field (fldiDFMIMOnGNWKJM) */
    URL_Bonifico_Prova?: string;
  };
}

/**
 * Marketing Sources table
 * Table ID: tblXyEscyPcP8TMLG
 * Generated from Airtable Metadata API
 */
export interface AirtableMarketingSources {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldAqFocZFBn3UJ8O) */
    ID: string;
    /** singleLineText field (fldJZYoCAdEj60B6y) */
    Name?: string;
    /** multilineText field (fld0of25wN3iu2SNQ) */
    Description?: string;
    /** checkbox field (fldgBYMJHwR66A3E3) */
    Active?: boolean;
    /** singleLineText field (fldigQ6L5BB9HpOpD) */
    Color?: string;
    /** multipleRecordLinks field (fldr9lUxIj5ZNkXYT) */
    Lead?: string[];
    /** multipleRecordLinks field (fldhFomevkCPjRHIF) */
    'Marketing Costs'?: string[];
  };
}

/**
 * Marketing Costs table
 * Table ID: tblHSmuFlSpKWAEjS
 * Generated from Airtable Metadata API
 */
export interface AirtableMarketingCosts {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldoWWh8HjyisSZPA) */
    ID: string;
    /** singleLineText field (fldBjbpHFY8ic0RVg) */
    Name?: string;
    /** multipleRecordLinks field (fldO0HxlGYuQXht9w) */
    Fonte?: string[];
    /** currency field (flduII49FCduShbI8) */
    Budget?: number;
    /** date field (fldTlvlbFgmy1pDwz) */
    'Data Inizio'?: string;
    /** date field (fldUbGwQL7QF0A2Xb) */
    'Data Fine'?: string;
    /** multilineText field (fldstm7FIpjOhWVfp) */
    Note?: string;
    /** multipleRecordLinks field (fldRoukIRCYIW3C3h) */
    'Spese Mensili'?: string[];
  };
}

/**
 * Spese Mensili table
 * Table ID: tblB6nZouVblmbzZu
 * Generated from Airtable Metadata API
 */
export interface AirtableSpeseMensili {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldupc5idytieOG31) */
    ID: string;
    /** multipleRecordLinks field (fldKxNBDWoFZPUPpe) */
    Campagna?: string[];
    /** currency field (fldFb5hRcCOh5UepS) */
    'Importo Speso'?: number;
    /** multilineText field (fldoZAUR4rbGiS6ic) */
    Note?: string;
    /** date field (fldpjti3etPXrtNbw) */
    'Data Inizio'?: string;
    /** date field (fldyiCelW1lRds8IG) */
    'Data Fine'?: string;
  };
}

/**
 * AI_Conversations table
 * Table ID: tblGJg2qS58L91AH4
 * Generated from Airtable Metadata API
 */
export interface AirtableAIConversations {
  id: string;
  createdTime: string;
  fields: {
    [key: string]: any;
    /** formula field (fldF87Vnu8SK8LEAn) */
    ID: string;
    /** singleLineText field (fld6OuEfjeDWWM8R5) */
    Tenant_ID?: string;
    /** singleLineText field (fldzxprYS764UClo9) */
    User_ID?: string;
    /** singleSelect field (fld60la8UgxB1L4xy) */
    Context?: 'Globale' | 'Attività' | 'Lead' | 'Ordine' | 'Cliente';
    /** singleLineText field (fldwsvVWjrZB1L4Db) */
    Context_ID?: string;
    /** multilineText field (fld6m3m2bXBRTZSjA) */
    Messages?: string;
    /** multilineText field (fld05KkGDzJeSU0Sj) */
    Summary?: string;
    /** createdTime field (fldbHyR6zasrxEGIH) */
    Created_At?: any;
    /** lastModifiedTime field (fldtkcrfz3evoQMDc) */
    Updated_At?: any;
  };
}

/**
 * Table ID constants
 */
export const AIRTABLE_TABLE_IDS = {
  LEAD: 'tblKIZ9CDjcQorONA',
  ACTIVITY: 'tblbcuRXKrWvne0Wy',
  NOTES: 'tblmvBiXtpQ2Qm0C7',
  USER: 'tbl141xF7ZQskCqGh',
  AUTOMATIONS: 'tblSd4GAZo9yHQvG0',
  PRODUCTS: 'tblEFvr3aT2jQdYUL',
  PRODUCT_VARIANTS: 'tblGnZgea6HlO2pJ4',
  PRODUCT_STRUCTURES: 'tbl58tZxGfEnLpUZA',
  ORDERS: 'tblkqfCMabBpVD1fP',
  ORDER_ITEMS: 'tblxzhMCa5UJOMZqC',
  PRODUCT_PRICE_HISTORY: 'tblXtMoiDwLEBG5WE',
  COMMISSION_PAYMENTS: 'tblbn6gRCwpmYICdZ',
  PAYMENT_TRANSACTIONS: 'tbl2bzbSxMDch72CY',
  MARKETING_SOURCES: 'tblXyEscyPcP8TMLG',
  MARKETING_COSTS: 'tblHSmuFlSpKWAEjS',
  SPESE_MENSILI: 'tblB6nZouVblmbzZu',
  AI_CONVERSATIONS: 'tblGJg2qS58L91AH4',
} as const;

/**
 * Table name to type mapping
 */
export type AirtableTableTypes = {
  'Lead': AirtableLead;
  'Activity': AirtableActivity;
  'Notes': AirtableNotes;
  'User': AirtableUser;
  'Automations': AirtableAutomations;
  'Products': AirtableProducts;
  'Product_Variants': AirtableProductVariants;
  'Product_Structures': AirtableProductStructures;
  'Orders': AirtableOrders;
  'Order_Items': AirtableOrderItems;
  'Product_Price_History': AirtableProductPriceHistory;
  'Commission_Payments': AirtableCommissionPayments;
  'Payment_Transactions': AirtablePaymentTransactions;
  'Marketing Sources': AirtableMarketingSources;
  'Marketing Costs': AirtableMarketingCosts;
  'Spese Mensili': AirtableSpeseMensili;
  'AI_Conversations': AirtableAIConversations;
};
